import json
import os
import subprocess
import sys

from dotenv import load_dotenv

load_dotenv()

FFPROBE_PATH = os.environ.get("FFPROBE_PATH", "ffprobe")
DOWNLOAD_FOLDER_PATH = os.environ.get("DOWNLOAD_FOLDER_PATH")

AUDIO_EXTENSIONS = {".mp3", ".wav", ".flac", ".ogg", ".m4a", ".aac", ".opus"}

# Substrings we look for in tag values (case-insensitive) as evidence of
# AI-generated provenance. This is a weak, easily-defeated signal: it only
# proves something when present, absence proves nothing (tags strip easily).
SUSPECT_KEYWORDS = [
    "suno",
    "udio",
    "riffusion",
    "musicgen",
    "stable audio",
    "ai-generated",
    "ai generated",
    "generated by",
    "synthesized",
]


def probe_tags(path: str) -> dict:
    result = subprocess.run(
        [FFPROBE_PATH, "-v", "quiet", "-print_format", "json", "-show_format", "-show_streams", path],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)
    tags = dict(data.get("format", {}).get("tags", {}))
    for stream in data.get("streams", []):
        tags.update(stream.get("tags", {}))
    return tags


def scan_file(path: str) -> dict:
    tags = probe_tags(path)
    hits = []
    for key, value in tags.items():
        haystack = f"{key} {value}".lower()
        for keyword in SUSPECT_KEYWORDS:
            if keyword in haystack:
                hits.append({"tag": key, "value": value, "matched": keyword})

    return {"file": path, "tags": tags, "suspect_hits": hits}


def scan_folder(folder: str) -> list[dict]:
    results = []
    for name in sorted(os.listdir(folder)):
        path = os.path.join(folder, name)
        if os.path.isfile(path) and os.path.splitext(name)[1].lower() in AUDIO_EXTENSIONS:
            try:
                results.append(scan_file(path))
            except subprocess.CalledProcessError as e:
                print(f"Could not probe '{path}': {e}", file=sys.stderr)
    return results


def main():
    target = sys.argv[1] if len(sys.argv) > 1 else DOWNLOAD_FOLDER_PATH
    if not target:
        print("No file/folder given and DOWNLOAD_FOLDER_PATH not set in .env", file=sys.stderr)
        sys.exit(1)

    if os.path.isdir(target):
        results = scan_folder(target)
    else:
        results = [scan_file(target)]

    for r in results:
        marker = "SUSPECT" if r["suspect_hits"] else "clean"
        print(f"[{marker}] {r['file']}")
        if r["suspect_hits"]:
            for hit in r["suspect_hits"]:
                print(f"    {hit['tag']} = {hit['value']!r}  (matched: {hit['matched']})")


if __name__ == "__main__":
    main()
